---
title: "Network Devices in Reinskis HomeNet"
devices:
  mediamachine:
    user: 'root'
    sudo: ''
  mediamachine-rp4:
    user: 'root'
    sudo: ''
  mediamachine-03: 
    user: 'root'
    sudo: ''
  octoprint: 
    user: 'pi'
    sudo: 'sudo'
  raspberrypi: 
    user: 'pi'
    sudo: 'sudo'
  reinski-tvh: 
    user: 'pi'
    sudo: 'sudo'
  reinskisnips: 
    user: 'pi'
    sudo: 'sudo'
  sarahpi:
    user: 'pi'
    sudo: 'sudo'