#!/bin/bash

source .venv/bin/activate
export FLASK_APP=app_src/webapp.py
export FLASK_APP_CONFIG=/home/pi/repositories/netdevices_manager/config.yml
python -m flask run --host=0.0.0.0 --reload --extra-files $FLASK_APP_CONFIG
